#!/usr/bin/env node
var fs = require('fs')
require('./')(
  //process.stdin,
  fs.createReadStream(process.argv[2]),
  function (error, data) {
  if (error) {
    console.error(error)
  } else {
    process.stdout.write(JSON.stringify(data, null, 2))
  }
})
